### ISSUE TITLE
Nonce missing

### ISSUE THREAD

**Issue by edraymundo** [aaronpk/quick-php-authentication#1]
Is nonce needed here and verified?

https://github.com/aaronpk/quick-php-authentication/blob/03b8e73bd064c75d51fd2f8270aa67778198d39e/index.php#L74

**Comment by aaronpk** [comment]
We're not doing OpenID here, so nonce is not required, since it's not part of OAuth. There is no ID token returned in this flow, which is where the nonce would appear.
