### ISSUE TITLE
400 bad request error when running the code

### ISSUE THREAD

**Issue by dongqiuyinggrace** [aaronpk/quick-php-authentication#8]
After git cloning the code and changed client_id, client_secret and metadata_url, and start php local server, I got the error: "404 bad request, Your request resulted in an error. 
Identity Provider: Unknown
Error Code: invalid_request
Description: Clients with 'application_type' of 'service' are not allowed to access the 'authorize' endpoint."

Please help me with it.

Thanks,
Grace

**Comment by aaronpk** [comment]
Sounds like you created the app at the oauth server as a "service" app. Try creating a new app as a "web server" app. Service apps means there's no user who is going to log in, so there is no need to do the authorization code flow with those apps.

**Comment by dongqiuyinggrace** [comment]
Thanks for your reply. But I couldn't find the button to create a web server app.

**Comment by dongqiuyinggrace** [comment]
I found it, I will try again, thanks.
